### ISSUE TITLE
Unclear docs

### ISSUE THREAD

**Issue by Jones-S** [unionco/craft-sync-db#2]
Hi there

 I would really like to use your plugin but the docs are a bit confusing.
First I think some prefilled settings in the config yaml would be very helpful.
I now have this:

_syncdb.yaml_
```yaml
skipTables: []
environments:
  -
    name: local DB
    username: root
    host: localhost
    root: /
    backupDirectory: /my/craft/root/path/storage/backups/databases/
    port: 22
    phpPath: /usr/local/php5/bin/php
    dbDumpClientPath: /Applications/MAMP/Library/bin/mysqldump  # Use pg_dump for Postgres
    environment: dev
```

But I guess I now have to add my remote db as well.
But also where do I set the passwords to make these ssh connections?

And what is happening if I run the sync button in my CP?
I guess it should somehow copy a db dump from the chosen environment. And then?
Will your plugin somehow import this dump into my local db?

Also the docs on the plugin site in the store are deprecated (config is still a php file etc.)
If you help me getting this to work I could do a fork and a PR to update some Readme stuff ...

Cheers
